# Generated by Django 6.0.4 on 2026-07-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_remove_equipment_application_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='equipmentcategorytranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='equipmentcategorytranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='EquipmentCategoryTranslation',
        ),
        migrations.DeleteModel(
            name='EquipmentCategory',
        ),
    ]
