# Generated by Django 6.0.4 on 2026-08-11 19:59

from django.db import migrations, models

EARTHWORKS_MLN_M3 = 50


def set_earthworks(apps, schema_editor):
    """Seed the singleton with the current earthworks volume.

    AddField leaves existing rows on the field default (0), so the value is
    written here. update_or_create also covers a fresh database, where the
    singleton row does not exist yet.
    """
    CompanyStats = apps.get_model('core', 'CompanyStats')
    CompanyStats.objects.update_or_create(
        pk=1,
        defaults={'earthworks_mln_m3': EARTHWORKS_MLN_M3},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_faqitem_answer_en_remove_faqitem_question_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystats',
            name='earthworks_mln_m3',
            field=models.PositiveIntegerField(default=0, verbose_name='Земляных работ, млн м³'),
        ),
        # Reverse is a no-op: reversing AddField drops the column anyway.
        migrations.RunPython(set_earthworks, migrations.RunPython.noop),
    ]
